sudo: required
language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw


addons:
  sonarcloud:
    organization: "dusanstevic"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./mvnw clean install -DskipTests=false -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  


deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: skynet-application